@startdot
digraph G {
_node1[label="inner declaration output , return:void"]
_node1parameters[label="parameters"]
_node2[label="local_dec N/A:local_dec"]
_node3[label="inner declaration input , return:int"]
_node3parameters[label="parameters"]
_node4[label="func_dec gcd , return:int"]
_node5[label="compound"]
_node5local_declaration[label="local_declaration"]
_node5sub_statements[label="sub statements"]
_node6[label="if"]
_node7[label="=="]
_node8[label="symbol_exp"]
_node9[label="local_dec v:local_dec"]
_node10[label="0:const_int"]
_node11[label="return_exp"]
_node12[label="symbol_exp"]
_node13[label="local_dec u:local_dec"]
_node6_else[label="else"]
_node14[label="return_exp"]
_node15[label="func_call"]
_node16[label="symbol_exp"]
_node15_arguments[label="arguments"]
_node17[label=","]
_node18[label="symbol_exp"]
_node19[label="-"]
_node20[label="*"]
_node21[label="/"]
_node22[label="symbol_exp"]
_node23[label="symbol_exp"]
_node24[label="symbol_exp"]
_node25[label="symbol_exp"]
_node4_parameters[label="parameters"]
_node13[label="local_dec u:local_dec"]
_node9[label="local_dec v:local_dec"]
_node28[label="func_dec foo , return:int"]
_node29[label="compound"]
_node29local_declaration[label="local_declaration"]
_node29sub_statements[label="sub statements"]
_node28_parameters[label="parameters"]
_node30[label="local_dec x:local_dec"]
_node31[label="local_dec y:local_dec"]
_node32[label="local_dec z:local_dec"]
_node33[label="func_dec fooa , return:int"]
_node34[label="compound"]
_node34local_declaration[label="local_declaration"]
_node34sub_statements[label="sub statements"]
_node33_parameters[label="parameters"]
_node35[label="func_dec fo , return:int"]
_node36[label="compound"]
_node36local_declaration[label="local_declaration"]
_node36sub_statements[label="sub statements"]
_node35_parameters[label="parameters"]
_node37[label="func_dec foob , return:void"]
_node38[label="compound"]
_node38local_declaration[label="local_declaration"]
_node38sub_statements[label="sub statements"]
_node37_parameters[label="parameters"]
_node39[label="func_dec main , return:void"]
_node40[label="compound"]
_node40local_declaration[label="local_declaration"]
_node40sub_statements[label="sub statements"]
_node41[label="local_dec x:local_dec"]
_node42[label="local_dec y:local_dec"]
_node43[label="compound"]
_node43local_declaration[label="local_declaration"]
_node43sub_statements[label="sub statements"]
_node44[label="!="]
_node45[label="symbol_exp"]
_node46[label="symbol_exp"]
_node47[label="=="]
_node48[label="symbol_exp"]
_node49[label="symbol_exp"]
_node50[label=">"]
_node51[label="symbol_exp"]
_node52[label="symbol_exp"]
_node53[label=">="]
_node54[label="symbol_exp"]
_node55[label="*"]
_node56[label="symbol_exp"]
_node57[label="2:const_int"]
_node58[label="<"]
_node59[label="symbol_exp"]
_node60[label="symbol_exp"]
_node61[label="+"]
_node62[label="symbol_exp"]
_node63[label="symbol_exp"]
_node64[label="-"]
_node65[label="symbol_exp"]
_node66[label="symbol_exp"]
_node67[label="*"]
_node68[label="symbol_exp"]
_node69[label="symbol_exp"]
_node70[label="/"]
_node71[label="symbol_exp"]
_node72[label="symbol_exp"]
_node73[label="<="]
_node74[label="symbol_exp"]
_node75[label="symbol_exp"]
_node76[label="compound"]
_node76local_declaration[label="local_declaration"]
_node76sub_statements[label="sub statements"]
_node77[label="local_dec x:local_dec"]
_node78[label="local_dec y:local_dec"]
_node79[label="func_call"]
_node80[label="symbol_exp"]
_node79_arguments[label="arguments"]
_node81[label="while"]
_node82[label="!="]
_node83[label="1:const_int"]
_node84[label="2:const_int"]
_node85[label="compound"]
_node85local_declaration[label="local_declaration"]
_node85sub_statements[label="sub statements"]
_node86[label="if"]
_node87[label="=="]
_node88[label="symbol_exp"]
_node89[label="1:const_int"]
_node90[label="func_call"]
_node91[label="symbol_exp"]
_node90_arguments[label="arguments"]
_node92[label="symbol_exp"]
_node86_else[label="else"]
_node93[label="func_call"]
_node94[label="symbol_exp"]
_node93_arguments[label="arguments"]
_node95[label="symbol_exp"]
_node96[label="assign_exp"]
_node97[label="symbol_exp"]
_node98[label="func_call"]
_node99[label="symbol_exp"]
_node98_arguments[label="arguments"]
_node100[label="assign_exp"]
_node101[label="symbol_exp"]
_node102[label="func_call"]
_node103[label="symbol_exp"]
_node102_arguments[label="arguments"]
_node104[label="func_call"]
_node105[label="symbol_exp"]
_node104_arguments[label="arguments"]
_node106[label="func_call"]
_node107[label="symbol_exp"]
_node106_arguments[label="arguments"]
_node108[label=","]
_node109[label="symbol_exp"]
_node110[label="symbol_exp"]
_node39_parameters[label="parameters"]
_node1->_node1parameters
_node1parameters->_node2
_node3->_node3parameters
_node5->_node5local_declaration
_node5->_node5sub_statements
_node8->_node9
_node7->_node8
_node7->_node10
_node12->_node13
_node11->_node12
_node6->_node6_else
_node16->_node4
_node15->_node16
_node15->_node15_arguments
_node18->_node9
_node22->_node13
_node23->_node9
_node21->_node22
_node21->_node23
_node24->_node9
_node20->_node21
_node20->_node24
_node25->_node13
_node19->_node20
_node19->_node25
_node17->_node18
_node17->_node19
_node15_arguments->_node17
_node14->_node15
_node6_else->_node14
_node6->_node7
_node6->_node11
_node5sub_statements->_node6
_node4->_node5
_node4->_node4_parameters
_node4_parameters->_node13
_node4_parameters->_node9
_node29->_node29local_declaration
_node29->_node29sub_statements
_node28->_node29
_node28->_node28_parameters
_node28_parameters->_node30
_node28_parameters->_node31
_node28_parameters->_node32
_node34->_node34local_declaration
_node34->_node34sub_statements
_node33->_node34
_node33->_node33_parameters
_node36->_node36local_declaration
_node36->_node36sub_statements
_node35->_node36
_node35->_node35_parameters
_node38->_node38local_declaration
_node38->_node38sub_statements
_node37->_node38
_node37->_node37_parameters
_node40->_node40local_declaration
_node40->_node40sub_statements
_node40local_declaration->_node41
_node40local_declaration->_node42
_node43->_node43local_declaration
_node43->_node43sub_statements
_node45->_node41
_node46->_node41
_node44->_node45
_node44->_node46
_node43sub_statements->_node44
_node48->_node41
_node49->_node42
_node47->_node48
_node47->_node49
_node43sub_statements->_node47
_node51->_node41
_node52->_node42
_node50->_node51
_node50->_node52
_node43sub_statements->_node50
_node54->_node41
_node56->_node42
_node55->_node56
_node55->_node57
_node53->_node54
_node53->_node55
_node43sub_statements->_node53
_node59->_node41
_node60->_node42
_node58->_node59
_node58->_node60
_node43sub_statements->_node58
_node62->_node42
_node63->_node41
_node61->_node62
_node61->_node63
_node43sub_statements->_node61
_node65->_node42
_node66->_node41
_node64->_node65
_node64->_node66
_node43sub_statements->_node64
_node68->_node41
_node69->_node42
_node67->_node68
_node67->_node69
_node43sub_statements->_node67
_node71->_node41
_node72->_node42
_node70->_node71
_node70->_node72
_node43sub_statements->_node70
_node74->_node41
_node75->_node42
_node73->_node74
_node73->_node75
_node43sub_statements->_node73
_node76->_node76local_declaration
_node76->_node76sub_statements
_node76local_declaration->_node77
_node76local_declaration->_node78
_node80->_node33
_node79->_node80
_node79->_node79_arguments
_node76sub_statements->_node79
_node82->_node83
_node82->_node84
_node85->_node85local_declaration
_node85->_node85sub_statements
_node88->_node78
_node87->_node88
_node87->_node89
_node91->_node1
_node90->_node91
_node90->_node90_arguments
_node92->_node78
_node90_arguments->_node92
_node86->_node86_else
_node94->_node1
_node93->_node94
_node93->_node93_arguments
_node95->_node78
_node93_arguments->_node95
_node86_else->_node93
_node86->_node87
_node86->_node90
_node85sub_statements->_node86
_node81->_node82
_node81->_node85
_node76sub_statements->_node81
_node43sub_statements->_node76
_node40sub_statements->_node43
_node97->_node41
_node99->_node3
_node98->_node99
_node98->_node98_arguments
_node96->_node97
_node96->_node98
_node40sub_statements->_node96
_node101->_node42
_node103->_node3
_node102->_node103
_node102->_node102_arguments
_node100->_node101
_node100->_node102
_node40sub_statements->_node100
_node105->_node1
_node104->_node105
_node104->_node104_arguments
_node107->_node4
_node106->_node107
_node106->_node106_arguments
_node109->_node41
_node110->_node42
_node108->_node109
_node108->_node110
_node106_arguments->_node108
_node104_arguments->_node106
_node40sub_statements->_node104
_node39->_node40
_node39->_node39_parameters

}
@enddot