@startdot
digraph G {
_node1[label="inner declaration output , return:void"]
_node1parameters[label="parameters"]
_node2[label="local_dec N/A:local_dec"]
_node3[label="inner declaration input , return:int"]
_node3parameters[label="parameters"]
_node4[label="func_dec gcd , return:int"]
_node5[label="compound"]
_node5local_declaration[label="local_declaration"]
_node5sub_statements[label="sub statements"]
_node6[label="if"]
_node7[label="=="]
_node8[label="symbol_exp"]
_node9[label="local_dec v:local_dec"]
_node10[label="0:const_int"]
_node11[label="return_exp"]
_node12[label="symbol_exp"]
_node13[label="local_dec u:local_dec"]
_node6_else[label="else"]
_node14[label="return_exp"]
_node15[label="func_call"]
_node16[label="symbol_exp"]
_node15_arguments[label="arguments"]
_node17[label=","]
_node18[label="symbol_exp"]
_node19[label="-"]
_node20[label="symbol_exp"]
_node21[label="*"]
_node22[label="/"]
_node23[label="symbol_exp"]
_node24[label="symbol_exp"]
_node25[label="symbol_exp"]
_node4_parameters[label="parameters"]
_node13[label="local_dec u:local_dec"]
_node9[label="local_dec v:local_dec"]
_node28[label="func_dec main , return:void"]
_node29[label="compound"]
_node29local_declaration[label="local_declaration"]
_node29sub_statements[label="sub statements"]
_node30[label="local_dec y:local_dec"]
_node31[label="local_dec x:local_dec"]
_node32[label="func_call"]
_node33[label="symbol_exp"]
_node32_arguments[label="arguments"]
_node34[label="+"]
_node35[label="+"]
_node36[label="123:const_int"]
_node37[label="/"]
_node38[label="*"]
_node39[label="231:const_int"]
_node40[label="3:const_int"]
_node41[label="0:const_int"]
_node42[label="123:const_int"]
_node43[label="assign_exp"]
_node44[label="symbol_exp"]
_node45[label="func_call"]
_node46[label="symbol_exp"]
_node45_arguments[label="arguments"]
_node47[label="assign_exp"]
_node48[label="symbol_exp"]
_node49[label="func_call"]
_node50[label="symbol_exp"]
_node49_arguments[label="arguments"]
_node51[label="func_call"]
_node52[label="symbol_exp"]
_node51_arguments[label="arguments"]
_node53[label="func_call"]
_node54[label="symbol_exp"]
_node53_arguments[label="arguments"]
_node55[label=","]
_node56[label="symbol_exp"]
_node57[label="symbol_exp"]
_node28_parameters[label="parameters"]
_node1->_node1parameters
_node1parameters->_node2
_node3->_node3parameters
_node5->_node5local_declaration
_node5->_node5sub_statements
_node8->_node9
_node7->_node8
_node7->_node10
_node12->_node13
_node11->_node12
_node6->_node6_else
_node16->_node4
_node15->_node16
_node15->_node15_arguments
_node18->_node9
_node20->_node13
_node23->_node13
_node24->_node9
_node22->_node23
_node22->_node24
_node25->_node9
_node21->_node22
_node21->_node25
_node19->_node20
_node19->_node21
_node17->_node18
_node17->_node19
_node15_arguments->_node17
_node14->_node15
_node6_else->_node14
_node6->_node7
_node6->_node11
_node5sub_statements->_node6
_node4->_node5
_node4->_node4_parameters
_node4_parameters->_node13
_node4_parameters->_node9
_node29->_node29local_declaration
_node29->_node29sub_statements
_node29local_declaration->_node30
_node29local_declaration->_node31
_node33->_node1
_node32->_node33
_node32->_node32_arguments
_node38->_node39
_node38->_node40
_node37->_node38
_node37->_node41
_node35->_node36
_node35->_node37
_node34->_node35
_node34->_node42
_node32_arguments->_node34
_node29sub_statements->_node32
_node44->_node31
_node46->_node3
_node45->_node46
_node45->_node45_arguments
_node43->_node44
_node43->_node45
_node29sub_statements->_node43
_node48->_node30
_node50->_node3
_node49->_node50
_node49->_node49_arguments
_node47->_node48
_node47->_node49
_node29sub_statements->_node47
_node52->_node1
_node51->_node52
_node51->_node51_arguments
_node54->_node4
_node53->_node54
_node53->_node53_arguments
_node56->_node31
_node57->_node30
_node55->_node56
_node55->_node57
_node53_arguments->_node55
_node51_arguments->_node53
_node29sub_statements->_node51
_node28->_node29
_node28->_node28_parameters

}
@enddot